import type { ECBlockInfo, ECLevel } from "@/types/ECCTable";

export const ECC_TABLE: {
  [version: number]: {
    [_LEVEL in ECLevel]: ECBlockInfo;
  };
} = {
  1: {
    L: {
      totalDataCodewords: 19,
      ecCodewordsPerBlock: 7,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 19,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    M: {
      totalDataCodewords: 16,
      ecCodewordsPerBlock: 10,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 16,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    Q: {
      totalDataCodewords: 13,
      ecCodewordsPerBlock: 13,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 13,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    H: {
      totalDataCodewords: 9,
      ecCodewordsPerBlock: 17,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 9,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
  },
  2: {
    L: {
      totalDataCodewords: 34,
      ecCodewordsPerBlock: 10,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 34,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    M: {
      totalDataCodewords: 28,
      ecCodewordsPerBlock: 16,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 28,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    Q: {
      totalDataCodewords: 22,
      ecCodewordsPerBlock: 22,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 22,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    H: {
      totalDataCodewords: 16,
      ecCodewordsPerBlock: 28,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 16,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
  },
  3: {
    L: {
      totalDataCodewords: 55,
      ecCodewordsPerBlock: 15,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 55,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    M: {
      totalDataCodewords: 44,
      ecCodewordsPerBlock: 26,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 44,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    Q: {
      totalDataCodewords: 34,
      ecCodewordsPerBlock: 18,
      numBlocksGroup1: 2,
      dataCodewordsGroup1: 17,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    H: {
      totalDataCodewords: 26,
      ecCodewordsPerBlock: 22,
      numBlocksGroup1: 2,
      dataCodewordsGroup1: 13,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
  },
  4: {
    L: {
      totalDataCodewords: 80,
      ecCodewordsPerBlock: 20,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 80,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    M: {
      totalDataCodewords: 64,
      ecCodewordsPerBlock: 18,
      numBlocksGroup1: 2,
      dataCodewordsGroup1: 32,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    Q: {
      totalDataCodewords: 48,
      ecCodewordsPerBlock: 26,
      numBlocksGroup1: 2,
      dataCodewordsGroup1: 24,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    H: {
      totalDataCodewords: 36,
      ecCodewordsPerBlock: 16,
      numBlocksGroup1: 4,
      dataCodewordsGroup1: 9,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
  },
  5: {
    L: {
      totalDataCodewords: 108,
      ecCodewordsPerBlock: 26,
      numBlocksGroup1: 1,
      dataCodewordsGroup1: 108,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    M: {
      totalDataCodewords: 86,
      ecCodewordsPerBlock: 24,
      numBlocksGroup1: 2,
      dataCodewordsGroup1: 43,
      numBlocksGroup2: 0,
      dataCodewordsGroup2: 0,
    },
    Q: {
      totalDataCodewords: 62,
      ecCodewordsPerBlock: 18,
      numBlocksGroup1: 2,
      dataCodewordsGroup1: 15,
      numBlocksGroup2: 2,
      dataCodewordsGroup2: 16,
    },
    H: {
      totalDataCodewords: 46,
      ecCodewordsPerBlock: 22,
      numBlocksGroup1: 2,
      dataCodewordsGroup1: 11,
      numBlocksGroup2: 2,
      dataCodewordsGroup2: 12,
    },
  },
};
